# https://kodiakhq.com/docs/recipes
version = 1

[merge]
  method                               = "squash"
  block_on_neutral_required_check_runs = true
  [merge.message]
    title = "pull_request_title"
    body  = "pull_request_body"
  [merge.automerge_dependencies]
    # auto merge all PRs opened by "dependabot" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
    versions  = ["minor", "patch"]
    usernames = ["dependabot"]
[update]
  ignored_usernames = ["dependabot", "renovate"]
